---
# Example string replacement rule
#- type: string
#  pattern: www.google.com
#  action: replace
#  value: google.com

- name: Remove formatting
  type: regex
  pattern: '</?(font|b|i).*?>'
  action: replace
  value: ""

#- name: Remove sync and corrected by...
#  type: regex
#  pattern: '(?i)sync(ed)?,?( and| &)?( corrected)?( by| -->) (\w+)?'
#  action: delete

#- name: Remove some well-known subtitle websites
#  type: regex
#  pattern: '(?i)(www\.)?(addic7ed.com|tvsubtitles.net)'
#  action: delete

- name: Remove double (or more) asterisk
  type: regex
  pattern: '\*{2,}'
  action: replace
  value: ""

- name: Remove ellipses at start of a line
  type: regex
  pattern: '^[.]+'
  action: replace
  value: ""

- name: Fix hyphens
  type: regex
  pattern: '[-]{3,}'
  action: replace
  value: '--'

- name: Remove lines with only an underscore
  type: regex
  pattern: '^(- )?_+'
  action: replace
  value: ""

- name: Remove unnecessary periods
  type: regex
  pattern: '([?!:])[.]+'
  action: replace
  value: '\1'

- name: Remove extra spaces
  type: regex
  pattern: '[\s]{2,}'
  action: replace
  value: " "

- name: Remove spaces at the beginning of a line
  type: regex
  pattern: '^\s+'
  action: replace
  value: ""

- name: Remove spaces at the end of a line
  type: regex
  pattern: '\s+$'
  action: "replace"
  value: ""
